server_script '@ElectronAC/src/include/server.lua'
client_script '@ElectronAC/src/include/client.lua'
shared_script '@fiveguard/ai_module_fg-obfuscated.lua'
fx_version 'cerulean'
game 'gta5'
author 'OneX.lt'
description '1X Ziuronai'
version 'v1.0'
lua54 'yes'
shared_script '@es_extended/imports.lua'
client_script 'client/main.lua'
server_script 'server/main.lua'